export const MONEDAS = [
  { code: 'CUP', name: 'Peso cubano' },
  { code: 'USD', name: 'Dólar estadounidense' },
  { code: 'EUR', name: 'Euro' },
  { code: 'JPY', name: 'Yen japonés' },
  { code: 'GBP', name: 'Libra esterlina' },
  { code: 'AUD', name: 'Dólar australiano' },
  { code: 'CAD', name: 'Dólar canadiense' },
  { code: 'CHF', name: 'Franco suizo' },
  { code: 'CNY', name: 'Yuan chino' },
  { code: 'HKD', name: 'Dólar de Hong Kong' },
  { code: 'NZD', name: 'Dólar neozelandés' },
  { code: 'SEK', name: 'Corona sueca' },
  { code: 'KRW', name: 'Won surcoreano' },
  { code: 'SGD', name: 'Dólar de Singapur' },
  { code: 'NOK', name: 'Corona noruega' },
  { code: 'MXN', name: 'Peso mexicano' },
  { code: 'INR', name: 'Rupia india' },
  { code: 'RUB', name: 'Rublo ruso' },
  { code: 'ZAR', name: 'Rand sudafricano' },
  { code: 'TRY', name: 'Lira turca' },
  { code: 'BRL', name: 'Real brasileño' },
  { code: 'TWD', name: 'Nuevo dólar de Taiwán' },
  { code: 'DKK', name: 'Corona danesa' },
  { code: 'PLN', name: 'Zloty polaco' },
  { code: 'THB', name: 'Baht tailandés' },
  { code: 'IDR', name: 'Rupia indonesia' },
  { code: 'HUF', name: 'Forinto húngaro' },
  { code: 'CZK', name: 'Corona checa' },
  { code: 'ILS', name: 'Nuevo séquel israelí' },
  { code: 'CLP', name: 'Peso chileno' },
  { code: 'PHP', name: 'Peso filipino' },
  { code: 'AED', name: 'Dirham de Emiratos Árabes Unidos' },
  { code: 'COP', name: 'Peso colombiano' },
  { code: 'SAR', name: 'Riyal saudí' },
  { code: 'MYR', name: 'Ringgit malayo' },
  { code: 'RON', name: 'Leu rumano' },
  { code: 'ARS', name: 'Peso argentino' },
  { code: 'PEN', name: 'Sol peruano' },
  { code: 'EGP', name: 'Libra egipcia' },
  { code: 'VND', name: 'Dong vietnamita' },
  { code: 'NGN', name: 'Naira nigeriana' },
];
